// This file contains a comprehensive list of all countries in the world
// Used to generate the complete flag database

using System.Collections.Generic;

public static class AllCountriesList
{
    public static List<CountryData> GetAllCountries()
    {
        return new List<CountryData>
        {
            // North America
            new CountryData("United States", new List<string> { "united states", "usa", "america", "us", "united states of america" }),
            new CountryData("Canada", new List<string> { "canada" }),
            new CountryData("Mexico", new List<string> { "mexico" }),
            new CountryData("Cuba", new List<string> { "cuba" }),
            new CountryData("Jamaica", new List<string> { "jamaica" }),
            new CountryData("Haiti", new List<string> { "haiti" }),
            new CountryData("Dominican Republic", new List<string> { "dominican republic", "dominican" }),
            new CountryData("Guatemala", new List<string> { "guatemala" }),
            new CountryData("Honduras", new List<string> { "honduras" }),
            new CountryData("El Salvador", new List<string> { "el salvador", "salvador" }),
            new CountryData("Nicaragua", new List<string> { "nicaragua" }),
            new CountryData("Costa Rica", new List<string> { "costa rica" }),
            new CountryData("Panama", new List<string> { "panama" }),
            new CountryData("Belize", new List<string> { "belize" }),
            new CountryData("Trinidad and Tobago", new List<string> { "trinidad and tobago", "trinidad", "tobago" }),
            new CountryData("Barbados", new List<string> { "barbados" }),
            new CountryData("Bahamas", new List<string> { "bahamas" }),
            
            // South America
            new CountryData("Brazil", new List<string> { "brazil", "brasil" }),
            new CountryData("Argentina", new List<string> { "argentina" }),
            new CountryData("Chile", new List<string> { "chile" }),
            new CountryData("Colombia", new List<string> { "colombia" }),
            new CountryData("Peru", new List<string> { "peru" }),
            new CountryData("Venezuela", new List<string> { "venezuela" }),
            new CountryData("Ecuador", new List<string> { "ecuador" }),
            new CountryData("Uruguay", new List<string> { "uruguay" }),
            new CountryData("Paraguay", new List<string> { "paraguay" }),
            new CountryData("Bolivia", new List<string> { "bolivia" }),
            new CountryData("Guyana", new List<string> { "guyana" }),
            new CountryData("Suriname", new List<string> { "suriname" }),
            
            // Europe
            new CountryData("United Kingdom", new List<string> { "united kingdom", "uk", "britain", "england", "great britain", "britannia" }),
            new CountryData("France", new List<string> { "france" }),
            new CountryData("Germany", new List<string> { "germany", "deutschland" }),
            new CountryData("Italy", new List<string> { "italy", "italia" }),
            new CountryData("Spain", new List<string> { "spain", "espana" }),
            new CountryData("Russia", new List<string> { "russia", "russian federation" }),
            new CountryData("Netherlands", new List<string> { "netherlands", "holland" }),
            new CountryData("Belgium", new List<string> { "belgium", "belgie" }),
            new CountryData("Switzerland", new List<string> { "switzerland", "schweiz" }),
            new CountryData("Austria", new List<string> { "austria", "osterreich" }),
            new CountryData("Sweden", new List<string> { "sweden", "sverige" }),
            new CountryData("Norway", new List<string> { "norway", "norge" }),
            new CountryData("Denmark", new List<string> { "denmark", "danmark" }),
            new CountryData("Finland", new List<string> { "finland", "suomi" }),
            new CountryData("Poland", new List<string> { "poland", "polska" }),
            new CountryData("Greece", new List<string> { "greece", "hellas" }),
            new CountryData("Portugal", new List<string> { "portugal" }),
            new CountryData("Ireland", new List<string> { "ireland", "eire" }),
            new CountryData("Czech Republic", new List<string> { "czech republic", "czechia", "czech" }),
            new CountryData("Romania", new List<string> { "romania" }),
            new CountryData("Hungary", new List<string> { "hungary", "magyarorszag" }),
            new CountryData("Bulgaria", new List<string> { "bulgaria" }),
            new CountryData("Croatia", new List<string> { "croatia" }),
            new CountryData("Serbia", new List<string> { "serbia" }),
            new CountryData("Slovakia", new List<string> { "slovakia" }),
            new CountryData("Slovenia", new List<string> { "slovenia" }),
            new CountryData("Lithuania", new List<string> { "lithuania" }),
            new CountryData("Latvia", new List<string> { "latvia" }),
            new CountryData("Estonia", new List<string> { "estonia" }),
            new CountryData("Luxembourg", new List<string> { "luxembourg" }),
            new CountryData("Iceland", new List<string> { "iceland" }),
            new CountryData("Malta", new List<string> { "malta" }),
            new CountryData("Cyprus", new List<string> { "cyprus" }),
            new CountryData("Albania", new List<string> { "albania" }),
            new CountryData("Macedonia", new List<string> { "macedonia", "north macedonia" }),
            new CountryData("Bosnia and Herzegovina", new List<string> { "bosnia and herzegovina", "bosnia", "herzegovina" }),
            new CountryData("Montenegro", new List<string> { "montenegro" }),
            new CountryData("Moldova", new List<string> { "moldova" }),
            new CountryData("Belarus", new List<string> { "belarus", "belorussia" }),
            new CountryData("Ukraine", new List<string> { "ukraine" }),
            new CountryData("Turkey", new List<string> { "turkey", "turkiye" }),
            
            // Asia
            new CountryData("China", new List<string> { "china", "peoples republic of china", "prc" }),
            new CountryData("Japan", new List<string> { "japan" }),
            new CountryData("India", new List<string> { "india" }),
            new CountryData("Indonesia", new List<string> { "indonesia" }),
            new CountryData("Pakistan", new List<string> { "pakistan" }),
            new CountryData("Bangladesh", new List<string> { "bangladesh" }),
            new CountryData("Philippines", new List<string> { "philippines", "philippine" }),
            new CountryData("Vietnam", new List<string> { "vietnam", "viet nam" }),
            new CountryData("Thailand", new List<string> { "thailand", "siam" }),
            new CountryData("South Korea", new List<string> { "south korea", "korea", "republic of korea", "rok" }),
            new CountryData("Malaysia", new List<string> { "malaysia" }),
            new CountryData("Singapore", new List<string> { "singapore" }),
            new CountryData("Myanmar", new List<string> { "myanmar", "burma" }),
            new CountryData("Sri Lanka", new List<string> { "sri lanka", "ceylon" }),
            new CountryData("Nepal", new List<string> { "nepal" }),
            new CountryData("Afghanistan", new List<string> { "afghanistan" }),
            new CountryData("Iran", new List<string> { "iran", "persia" }),
            new CountryData("Iraq", new List<string> { "iraq" }),
            new CountryData("Saudi Arabia", new List<string> { "saudi arabia", "saudi" }),
            new CountryData("United Arab Emirates", new List<string> { "united arab emirates", "uae", "emirates" }),
            new CountryData("Israel", new List<string> { "israel" }),
            new CountryData("Jordan", new List<string> { "jordan" }),
            new CountryData("Lebanon", new List<string> { "lebanon" }),
            new CountryData("Syria", new List<string> { "syria" }),
            new CountryData("Yemen", new List<string> { "yemen" }),
            new CountryData("Oman", new List<string> { "oman" }),
            new CountryData("Kuwait", new List<string> { "kuwait" }),
            new CountryData("Qatar", new List<string> { "qatar" }),
            new CountryData("Bahrain", new List<string> { "bahrain" }),
            new CountryData("Kazakhstan", new List<string> { "kazakhstan" }),
            new CountryData("Uzbekistan", new List<string> { "uzbekistan" }),
            new CountryData("Kyrgyzstan", new List<string> { "kyrgyzstan" }),
            new CountryData("Tajikistan", new List<string> { "tajikistan" }),
            new CountryData("Turkmenistan", new List<string> { "turkmenistan" }),
            new CountryData("Mongolia", new List<string> { "mongolia" }),
            new CountryData("Cambodia", new List<string> { "cambodia" }),
            new CountryData("Laos", new List<string> { "laos" }),
            new CountryData("Brunei", new List<string> { "brunei", "brunei darussalam" }),
            new CountryData("East Timor", new List<string> { "east timor", "timor leste" }),
            new CountryData("Bhutan", new List<string> { "bhutan" }),
            new CountryData("Maldives", new List<string> { "maldives" }),
            
            // Africa
            new CountryData("South Africa", new List<string> { "south africa" }),
            new CountryData("Egypt", new List<string> { "egypt", "egyptian arab republic" }),
            new CountryData("Nigeria", new List<string> { "nigeria" }),
            new CountryData("Kenya", new List<string> { "kenya" }),
            new CountryData("Ethiopia", new List<string> { "ethiopia" }),
            new CountryData("Ghana", new List<string> { "ghana" }),
            new CountryData("Tanzania", new List<string> { "tanzania" }),
            new CountryData("Morocco", new List<string> { "morocco", "maroc" }),
            new CountryData("Algeria", new List<string> { "algeria" }),
            new CountryData("Sudan", new List<string> { "sudan" }),
            new CountryData("South Sudan", new List<string> { "south sudan" }),
            new CountryData("Uganda", new List<string> { "uganda" }),
            new CountryData("Angola", new List<string> { "angola" }),
            new CountryData("Mozambique", new List<string> { "mozambique" }),
            new CountryData("Madagascar", new List<string> { "madagascar" }),
            new CountryData("Cameroon", new List<string> { "cameroon" }),
            new CountryData("Ivory Coast", new List<string> { "ivory coast", "cote divoire" }),
            new CountryData("Niger", new List<string> { "niger" }),
            new CountryData("Mali", new List<string> { "mali" }),
            new CountryData("Burkina Faso", new List<string> { "burkina faso" }),
            new CountryData("Malawi", new List<string> { "malawi" }),
            new CountryData("Zambia", new List<string> { "zambia" }),
            new CountryData("Zimbabwe", new List<string> { "zimbabwe" }),
            new CountryData("Senegal", new List<string> { "senegal" }),
            new CountryData("Chad", new List<string> { "chad" }),
            new CountryData("Guinea", new List<string> { "guinea" }),
            new CountryData("Rwanda", new List<string> { "rwanda" }),
            new CountryData("Benin", new List<string> { "benin" }),
            new CountryData("Burundi", new List<string> { "burundi" }),
            new CountryData("Tunisia", new List<string> { "tunisia" }),
            new CountryData("Libya", new List<string> { "libya" }),
            new CountryData("Somalia", new List<string> { "somalia" }),
            new CountryData("Eritrea", new List<string> { "eritrea" }),
            new CountryData("Mauritania", new List<string> { "mauritania" }),
            new CountryData("Sierra Leone", new List<string> { "sierra leone" }),
            new CountryData("Togo", new List<string> { "togo" }),
            new CountryData("Liberia", new List<string> { "liberia" }),
            new CountryData("Central African Republic", new List<string> { "central african republic", "car" }),
            new CountryData("Congo", new List<string> { "congo", "republic of the congo" }),
            new CountryData("Democratic Republic of the Congo", new List<string> { "democratic republic of the congo", "drc", "zaire" }),
            new CountryData("Gabon", new List<string> { "gabon" }),
            new CountryData("Equatorial Guinea", new List<string> { "equatorial guinea" }),
            new CountryData("Botswana", new List<string> { "botswana" }),
            new CountryData("Namibia", new List<string> { "namibia" }),
            new CountryData("Lesotho", new List<string> { "lesotho" }),
            new CountryData("Swaziland", new List<string> { "swaziland", "eswatini" }),
            new CountryData("Mauritius", new List<string> { "mauritius" }),
            new CountryData("Djibouti", new List<string> { "djibouti" }),
            new CountryData("Comoros", new List<string> { "comoros" }),
            new CountryData("Cape Verde", new List<string> { "cape verde" }),
            new CountryData("Sao Tome and Principe", new List<string> { "sao tome and principe" }),
            new CountryData("Gambia", new List<string> { "gambia" }),
            new CountryData("Guinea Bissau", new List<string> { "guinea bissau" }),
            
            // Oceania
            new CountryData("Australia", new List<string> { "australia" }),
            new CountryData("New Zealand", new List<string> { "new zealand", "aotearoa" }),
            new CountryData("Papua New Guinea", new List<string> { "papua new guinea", "png" }),
            new CountryData("Fiji", new List<string> { "fiji" }),
            new CountryData("Solomon Islands", new List<string> { "solomon islands" }),
            new CountryData("Vanuatu", new List<string> { "vanuatu" }),
            new CountryData("Samoa", new List<string> { "samoa" }),
            new CountryData("Kiribati", new List<string> { "kiribati" }),
            new CountryData("Micronesia", new List<string> { "micronesia", "federated states of micronesia" }),
            new CountryData("Marshall Islands", new List<string> { "marshall islands" }),
            new CountryData("Palau", new List<string> { "palau" }),
            new CountryData("Tonga", new List<string> { "tonga" }),
            new CountryData("Tuvalu", new List<string> { "tuvalu" }),
            new CountryData("Nauru", new List<string> { "nauru" })
        };
    }
}

public class CountryData
{
    public string countryName;
    public List<string> acceptedAnswers;
    
    public CountryData(string name, List<string> answers)
    {
        countryName = name;
        acceptedAnswers = answers;
    }
}

