using System.Collections.Generic;

// Maps country names to ISO 3166-1 alpha-2 codes for flag file naming
public static class CountryISOMapping
{
    private static Dictionary<string, string> countryToISO = new Dictionary<string, string>
    {
        // North America
        { "United States", "us" },
        { "Canada", "ca" },
        { "Mexico", "mx" },
        { "Cuba", "cu" },
        { "Jamaica", "jm" },
        { "Haiti", "ht" },
        { "Dominican Republic", "do" },
        { "Guatemala", "gt" },
        { "Honduras", "hn" },
        { "El Salvador", "sv" },
        { "Nicaragua", "ni" },
        { "Costa Rica", "cr" },
        { "Panama", "pa" },
        { "Belize", "bz" },
        { "Trinidad and Tobago", "tt" },
        { "Barbados", "bb" },
        { "Bahamas", "bs" },
        
        // South America
        { "Brazil", "br" },
        { "Argentina", "ar" },
        { "Chile", "cl" },
        { "Colombia", "co" },
        { "Peru", "pe" },
        { "Venezuela", "ve" },
        { "Ecuador", "ec" },
        { "Uruguay", "uy" },
        { "Paraguay", "py" },
        { "Bolivia", "bo" },
        { "Guyana", "gy" },
        { "Suriname", "sr" },
        
        // Europe
        { "United Kingdom", "gb" },
        { "France", "fr" },
        { "Germany", "de" },
        { "Italy", "it" },
        { "Spain", "es" },
        { "Russia", "ru" },
        { "Netherlands", "nl" },
        { "Belgium", "be" },
        { "Switzerland", "ch" },
        { "Austria", "at" },
        { "Sweden", "se" },
        { "Norway", "no" },
        { "Denmark", "dk" },
        { "Finland", "fi" },
        { "Poland", "pl" },
        { "Greece", "gr" },
        { "Portugal", "pt" },
        { "Ireland", "ie" },
        { "Czech Republic", "cz" },
        { "Romania", "ro" },
        { "Hungary", "hu" },
        { "Bulgaria", "bg" },
        { "Croatia", "hr" },
        { "Serbia", "rs" },
        { "Slovakia", "sk" },
        { "Slovenia", "si" },
        { "Lithuania", "lt" },
        { "Latvia", "lv" },
        { "Estonia", "ee" },
        { "Luxembourg", "lu" },
        { "Iceland", "is" },
        { "Malta", "mt" },
        { "Cyprus", "cy" },
        { "Albania", "al" },
        { "Macedonia", "mk" },
        { "Bosnia and Herzegovina", "ba" },
        { "Montenegro", "me" },
        { "Moldova", "md" },
        { "Belarus", "by" },
        { "Ukraine", "ua" },
        { "Turkey", "tr" },
        
        // Asia
        { "China", "cn" },
        { "Japan", "jp" },
        { "India", "in" },
        { "Indonesia", "id" },
        { "Pakistan", "pk" },
        { "Bangladesh", "bd" },
        { "Philippines", "ph" },
        { "Vietnam", "vn" },
        { "Thailand", "th" },
        { "South Korea", "kr" },
        { "Malaysia", "my" },
        { "Singapore", "sg" },
        { "Myanmar", "mm" },
        { "Sri Lanka", "lk" },
        { "Nepal", "np" },
        { "Afghanistan", "af" },
        { "Iran", "ir" },
        { "Iraq", "iq" },
        { "Saudi Arabia", "sa" },
        { "United Arab Emirates", "ae" },
        { "Israel", "il" },
        { "Jordan", "jo" },
        { "Lebanon", "lb" },
        { "Syria", "sy" },
        { "Yemen", "ye" },
        { "Oman", "om" },
        { "Kuwait", "kw" },
        { "Qatar", "qa" },
        { "Bahrain", "bh" },
        { "Kazakhstan", "kz" },
        { "Uzbekistan", "uz" },
        { "Kyrgyzstan", "kg" },
        { "Tajikistan", "tj" },
        { "Turkmenistan", "tm" },
        { "Mongolia", "mn" },
        { "Cambodia", "kh" },
        { "Laos", "la" },
        { "Brunei", "bn" },
        { "East Timor", "tl" },
        { "Bhutan", "bt" },
        { "Maldives", "mv" },
        
        // Africa
        { "South Africa", "za" },
        { "Egypt", "eg" },
        { "Nigeria", "ng" },
        { "Kenya", "ke" },
        { "Ethiopia", "et" },
        { "Ghana", "gh" },
        { "Tanzania", "tz" },
        { "Morocco", "ma" },
        { "Algeria", "dz" },
        { "Sudan", "sd" },
        { "South Sudan", "ss" },
        { "Uganda", "ug" },
        { "Angola", "ao" },
        { "Mozambique", "mz" },
        { "Madagascar", "mg" },
        { "Cameroon", "cm" },
        { "Ivory Coast", "ci" },
        { "Niger", "ne" },
        { "Mali", "ml" },
        { "Burkina Faso", "bf" },
        { "Malawi", "mw" },
        { "Zambia", "zm" },
        { "Zimbabwe", "zw" },
        { "Senegal", "sn" },
        { "Chad", "td" },
        { "Guinea", "gn" },
        { "Rwanda", "rw" },
        { "Benin", "bj" },
        { "Burundi", "bi" },
        { "Tunisia", "tn" },
        { "Libya", "ly" },
        { "Somalia", "so" },
        { "Eritrea", "er" },
        { "Mauritania", "mr" },
        { "Sierra Leone", "sl" },
        { "Togo", "tg" },
        { "Liberia", "lr" },
        { "Central African Republic", "cf" },
        { "Congo", "cg" },
        { "Democratic Republic of the Congo", "cd" },
        { "Gabon", "ga" },
        { "Equatorial Guinea", "gq" },
        { "Botswana", "bw" },
        { "Namibia", "na" },
        { "Lesotho", "ls" },
        { "Swaziland", "sz" },
        { "Mauritius", "mu" },
        { "Djibouti", "dj" },
        { "Comoros", "km" },
        { "Cape Verde", "cv" },
        { "Sao Tome and Principe", "st" },
        { "Gambia", "gm" },
        { "Guinea Bissau", "gw" },
        
        // Oceania
        { "Australia", "au" },
        { "New Zealand", "nz" },
        { "Papua New Guinea", "pg" },
        { "Fiji", "fj" },
        { "Solomon Islands", "sb" },
        { "Vanuatu", "vu" },
        { "Samoa", "ws" },
        { "Kiribati", "ki" },
        { "Micronesia", "fm" },
        { "Marshall Islands", "mh" },
        { "Palau", "pw" },
        { "Tonga", "to" },
        { "Tuvalu", "tv" },
        { "Nauru", "nr" }
    };
    
    public static string GetISOCode(string countryName)
    {
        if (countryToISO.TryGetValue(countryName, out string isoCode))
        {
            return isoCode;
        }
        return null;
    }
}

